### ISSUE TITLE
I have an error while running CoverageJsonReader

### ISSUE THREAD

**Issue by junghuk** [spideruci/tacoco#13] opened 2015-05-27 06:12 UTC
I have an error with CoverageJsonReader.
I attach the stack trace.

For the test, 
You can get my project from: https://github.com/junghuk/text
Command for analyzer: mvn exec:java -Panalyzer -Dexec.args="/Users/bada/git/test/text ./jacoco.exec ./tacoco.json DENSE false"
Command for reader: mvn exec:java -Preader -Dexec.args="tacoco.json"
I attach jacoco.exec and tacoco.json on slack.

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project tacoco: An exception occured while executing the Java class. null: InvocationTargetException: End of input at line 85 column 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project tacoco: An exception occured while executing the Java class. null
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. null
    at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:345)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: End of input at line 85 column 1
    at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:553)
    at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
    at org.spideruci.tacoco.reporting.CoverageJsonReader.hasNext(CoverageJsonReader.java:66)
    at org.spideruci.tacoco.reporting.CoverageJsonReader.read(CoverageJsonReader.java:95)
    at org.spideruci.tacoco.reporting.CoverageJsonReader.main(CoverageJsonReader.java:30)
    ... 6 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by VijayKrishna** [comment] 2015-05-27 06:50
Diagnosis: the ExecutionDataParser, expects the last session to have the id, `end` (this is related to Issue #3). When it sees that the `end` session has been reached, it properly terminates the printing of the JSON dump, by adding a closing bracket in the of the dump.

Now, in the case of commons-text, that is not the last session, instead this is the last recorded session id: `testMissingMetric(org.apache.commons.text.similarity.StringMetricFromTest)`. Because it never encounters the `end` session, it never properly terminates the JSON dump with the closing bracket.

And so, when this "incomplete" JSON dump is read by the CoverageJsonReader, it expects more JSON elements at the end, because the JSON was never properly terminated. And so, while it is trying to read in the next non-whitespace character at the end of the JSON, it sees that it has reached the End-Of-File, and thus throws an exception, as shown in the stacktrace:

```
 Caused by: java.io.EOFException: End of input at line 85 column 1
at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)
```

So, the root cause seems to be with the TacocoListener itself that for some reason never records the `end` session. I will open another issue for that. But for now, i will submit a quick-fix for this.

**Comment by VijayKrishna** [comment] 2015-05-27 07:18
@junghuk: i just patched a quick fix for this bug. by the way, this was a good catch -- looks like there is a deeper issue at play here, that i am investigating. But this issue should now be resolved. The CoverageJsonReader should execute without throwing any error. 

The CoverageJsonReader will print out a whole bunch of 1's and 0's in the end, and finally print out a lot of JSON. That is nothing but the coverage matrix. If you see that output on the console, it working as expected. If that is the case, please let me know -- i will go ahead and close this issue.

**Comment by VijayKrishna** [comment] 2015-05-27 22:11
the implementation no longer depends on the `end` session. JSON dump now closed properly with an empty array.

**Closed as completed by VijayKrishna** 2015-05-27 22:11 UTC
Labels: bug
